Mail improvements and other config install
- Other config refers to configuration outside of the users home
  directory and therefore cannot be tracked by Chezmoi. It is installed
  with a script.
- Mail improvements mostly involve tagging mail for wildcard url and
  better syncing etc.

diff --git a/dot_local/bin/executable_sendmail b/dot_local/bin/executable_sendmail
--- a/dot_local/bin/executable_sendmail
+++ b/dot_local/bin/executable_sendmail
@@ -1,4 +1,6 @@
 #!/bin/sh
 input=`cat`
-echo "$input" | /usr/bin/msmtp -C $HOME/.config/msmtp/msmtprc --read-envelope-from -a $1
-echo "$input" | notmuch insert --folder $1/Sent +sent 
+echo "$input" | /usr/bin/msmtp -C $HOME/.config/msmtp/msmtprc \
+    --read-envelope-from --read-recipients -a $1  \
+    && echo "$input" | notmuch insert --folder $1/Sent +sent \
+    || echo "Failed to send mail"
